# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microbiologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=15)),
                ('ufc', models.IntegerField(verbose_name='UFC/ml')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='microbiologia',
            name='origen_agua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.OrigenAgua'),
        ),
    ]
