# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
