# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_auto_20170121_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbiologia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
