# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maduracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maduracion',
            name='copula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='descarte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='factura_nauplios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='nauplio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='ovas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
