# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0006_auto_20170110_1108'),
        ('app_maduracion', '0002_auto_20170109_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='maduracion',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Sala'),
            preserve_default=False,
        ),
    ]
