# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maduracion', '0003_maduracion_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maduracion',
            name='copula',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
