# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maduracion', '0005_auto_20170820_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maduracion',
            name='copula',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='descarte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='factura_nauplios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='nauplio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maduracion',
            name='ovas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
