# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maduracion', '0006_auto_20170821_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='maduracion',
            name='nauplios_hembra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nauplios/Hembra'),
        ),
    ]
