# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLarva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblacion_inicial', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('numero_ciclo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatoParametroAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pH')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oxigeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salinidad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-fecha_ingreso', 'sala'],
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ciclo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaLarva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_dia', models.SmallIntegerField()),
                ('retraso', models.SmallIntegerField(verbose_name='Porcentaje de retraso')),
                ('mortalidad', models.SmallIntegerField(verbose_name='Porcentaje de mortalidad')),
                ('deformidad', models.SmallIntegerField(verbose_name='Porcentaje de deformidad')),
                ('poblacion', models.PositiveIntegerField(verbose_name='Poblaci\xf3n actual')),
                ('supervivencia', models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de supervivencia')),
                ('imm', models.CharField(blank=True, max_length=25, null=True, verbose_name='\xcdndice de masa muscular')),
                ('ciclo_larva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.CicloLarva')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Modulo')),
            ],
        ),
        migrations.AddField(
            model_name='datoparametroagua',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Sala'),
        ),
        migrations.AddField(
            model_name='ciclolarva',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Estado'),
        ),
        migrations.AddField(
            model_name='ciclolarva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Sala'),
        ),
    ]
