# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0002_modulo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolarva',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciclolarva',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
