# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0003_auto_20170107_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolarva',
            name='numero_ciclo',
            field=models.SmallIntegerField(verbose_name='N\xfamero de ciclo'),
        ),
        migrations.AlterField(
            model_name='ciclolarva',
            name='poblacion_inicial',
            field=models.PositiveIntegerField(verbose_name='Poblaci\xf3n inicial'),
        ),
    ]
