# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0004_auto_20170109_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoparametroagua',
            options={'ordering': ['-fecha_ingreso', 'ciclo']},
        ),
        migrations.RemoveField(
            model_name='datoparametroagua',
            name='sala',
        ),
        migrations.AddField(
            model_name='datoparametroagua',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.CicloLarva'),
        ),
    ]
