# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0005_auto_20170109_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoparametroagua',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.CicloLarva'),
            preserve_default=False,
        ),
    ]
