# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0007_auto_20170124_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidalarva',
            name='deformidad',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de deformidad'),
        ),
        migrations.AlterField(
            model_name='medidalarva',
            name='estadio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Estadio'),
        ),
        migrations.AlterField(
            model_name='medidalarva',
            name='mortalidad',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de mortalidad'),
        ),
        migrations.AlterField(
            model_name='medidalarva',
            name='numero_dia',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidalarva',
            name='poblacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Poblaci\xf3n actual'),
        ),
        migrations.AlterField(
            model_name='medidalarva',
            name='retraso',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de retraso'),
        ),
    ]
