# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0009_auto_20170205_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedidaLarva',
            new_name='DatosLarva',
        ),
    ]
