# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0010_auto_20170205_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoslarva',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_larvarios.Estadio', verbose_name='Estad\xedo (requerido)'),
        ),
    ]
