# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_larvarios', '0011_auto_20170208_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslarva',
            name='numero_dia',
        ),
    ]
