# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_algas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alga',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
