# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_algas', '0003_alga_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alga',
            name='cm',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CM (Chaetoceros muelleri)'),
        ),
        migrations.AlterField(
            model_name='alga',
            name='nv',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='NV (Navicula)'),
        ),
        migrations.AlterField(
            model_name='alga',
            name='t',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='T (Tetraselmis)'),
        ),
        migrations.AlterField(
            model_name='alga',
            name='tw',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='TW (Thalassiosira weissflogii)'),
        ),
    ]
